---
- name: Power On VMs
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware
  pre_tasks:
    - include_vars: VMVars.yaml
  tasks:
    - name: Power On VMs
      vmware_guest_powerstate:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        name: "New Ubuntu VM - {{ item }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        state: powered-on
      register: powerup
      ignore_errors: true
      loop: "{{ range(1, vm_count + 1, 1) | list }}"
